# Generated by Django 5.1.1 on 2024-12-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fechaa'),
        ),
    ]
